// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-joEz22d8IJ2QEbSxNg6s4hawZ4qi78A',
    appId: '1:668457735767:web:062e9049c5db0b30fef512',
    messagingSenderId: '668457735767',
    projectId: 'cavpool',
    authDomain: 'cavpool.firebaseapp.com',
    storageBucket: 'cavpool.firebasestorage.app',
    measurementId: 'G-E3YW0RN7QZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUy-XUIrLdVXwuUIdlGZIIEtaur414gpo',
    appId: '1:668457735767:android:5136de81a3832689fef512',
    messagingSenderId: '668457735767',
    projectId: 'cavpool',
    storageBucket: 'cavpool.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh-Ql_CHjJpsQAypisXmfIJH5t2LasJGQ',
    appId: '1:668457735767:ios:00984891cd761c21fef512',
    messagingSenderId: '668457735767',
    projectId: 'cavpool',
    storageBucket: 'cavpool.firebasestorage.app',
    iosClientId: '668457735767-6jovnnlisdbaam050he544234579di1f.apps.googleusercontent.com',
    iosBundleId: 'edu.virginia.cs4971.capstoneOrange1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh-Ql_CHjJpsQAypisXmfIJH5t2LasJGQ',
    appId: '1:668457735767:ios:00984891cd761c21fef512',
    messagingSenderId: '668457735767',
    projectId: 'cavpool',
    storageBucket: 'cavpool.firebasestorage.app',
    iosClientId: '668457735767-6jovnnlisdbaam050he544234579di1f.apps.googleusercontent.com',
    iosBundleId: 'edu.virginia.cs4971.capstoneOrange1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-joEz22d8IJ2QEbSxNg6s4hawZ4qi78A',
    appId: '1:668457735767:web:9ce37cde65ddcc70fef512',
    messagingSenderId: '668457735767',
    projectId: 'cavpool',
    authDomain: 'cavpool.firebaseapp.com',
    storageBucket: 'cavpool.firebasestorage.app',
    measurementId: 'G-VL5J718K5S',
  );

}