import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import '../models/safety_event_model.dart';
import '../models/notification_model.dart';
import '../utils/security_utils.dart';
import 'notification_service.dart';
import 'location_service.dart';
import 'notification_delivery_service.dart';

class SafetyService {
  static final SafetyService _instance = SafetyService._internal();
  factory SafetyService() => _instance;
  SafetyService._internal();

  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final String _collection = 'safety_events';
  final NotificationService _notificationService = NotificationService();
  final LocationService _locationService = LocationService();
  final NotificationDeliveryService _deliveryService = NotificationDeliveryService();

  // Create a new safety event
  Future<String?> createSafetyEvent(SafetyEventModel event) async {
    try {
      // Validate and sanitize data before storing
      final eventMap = event.toMap();
      final validationErrors = SecurityUtils.validateSafetyEventData(eventMap);
      
      if (validationErrors.isNotEmpty) {
        debugPrint('Safety event validation failed: $validationErrors');
        SecurityUtils.logSecurityEvent('invalid_safety_event_data', {
          'errors': validationErrors,
          'eventType': event.eventType.name,
        });
        return null;
      }

      // Create event with sanitized data
      final docRef = await _firestore.collection(_collection).add(eventMap);
      debugPrint('Created safety event: ${docRef.id}');
      
      // Log security event for audit trail
      SecurityUtils.logSecurityEvent('safety_event_created', {
        'eventId': docRef.id,
        'eventType': event.eventType.name,
        'severity': event.severity.name,
        'reporterId': SecurityUtils.hashData(event.reporterId),
      });
      
      // Auto-notify admins for critical events
      if (event.severity == SafetyEventSeverity.critical) {
        await _notifyAdminsOfCriticalEvent(event.copyWith(id: docRef.id));
      }
      
      // Check for multiple reports against same user
      if (event.reportedUserId != null) {
        await _checkMultipleReports(event.reportedUserId!);
      }
      
      return docRef.id;
    } catch (e) {
      debugPrint('Error creating safety event: $e');
      SecurityUtils.logSecurityEvent('safety_event_creation_error', {
        'error': e.toString(),
        'eventType': event.eventType.name,
      });
      return null;
    }
  }

  // Report a safety incident from user
  Future<String?> reportSafetyIncident({
    required String reporterId,
    required SafetyIncidentType incidentType,
    required String title,
    required String description,
    String? reportedUserId,
    String? rideId,
    SafetyEventSeverity severity = SafetyEventSeverity.medium,
    List<SafetyEventEvidence> evidence = const [],
    bool isAnonymous = false,
  }) async {
    try {
      // Get current location if available
      final location = await _getCurrentLocationForEvent();
      
      final event = SafetyEventModel(
        id: '',
        eventType: SafetyEventType.userReported,
        incidentType: incidentType,
        reporterId: reporterId,
        reportedUserId: reportedUserId,
        rideId: rideId,
        title: title,
        description: description,
        severity: severity,
        status: SafetyEventStatus.pending,
        location: location,
        evidence: evidence,
        metadata: {
          'reportMethod': 'in_app_form',
          'deviceInfo': await _getDeviceInfo(),
        },
        timestamp: DateTime.now(),
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        tags: _generateTags(incidentType, severity),
        isAnonymous: isAnonymous,
        systemData: {
          'autoGenerated': false,
          'sourceService': 'user_report',
        },
      );

      final eventId = await createSafetyEvent(event);
      
      if (eventId != null) {
        // Send confirmation to reporter
        await _sendReportConfirmation(reporterId, eventId, isAnonymous);
      }
      
      return eventId;
    } catch (e) {
      debugPrint('Error reporting safety incident: $e');
      return null;
    }
  }

  // Log emergency button activation
  Future<String?> logEmergencyButtonActivation({
    required String userId,
    String? rideId,
    Map<String, dynamic>? additionalContext,
  }) async {
    try {
      final location = await _getCurrentLocationForEvent();
      
      final event = SafetyEventModel(
        id: '',
        eventType: SafetyEventType.emergencyButton,
        incidentType: null,
        reporterId: userId,
        reportedUserId: null,
        rideId: rideId,
        title: 'Emergency Button Activated',
        description: 'User activated emergency button during ${rideId != null ? 'ride' : 'app usage'}',
        severity: SafetyEventSeverity.critical,
        status: SafetyEventStatus.pending,
        location: location,
        evidence: [],
        metadata: {
          'activationMethod': 'emergency_button',
          'context': additionalContext ?? {},
          'requiresImmediateResponse': true,
        },
        timestamp: DateTime.now(),
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        tags: ['emergency', 'critical', 'immediate_response'],
        isAnonymous: false,
        systemData: {
          'autoGenerated': true,
          'sourceService': 'emergency_button',
          'priority': 'highest',
        },
      );

      final eventId = await createSafetyEvent(event);
      
      if (eventId != null) {
        // Immediate critical notifications
        await _handleEmergencyResponse(event.copyWith(id: eventId));
      }
      
      return eventId;
    } catch (e) {
      debugPrint('Error logging emergency button activation: $e');
      return null;
    }
  }

  // Log ride cancellation with safety reason
  Future<String?> logSafetyCancellation({
    required String userId,
    required String rideId,
    required String reason,
    SafetyEventSeverity severity = SafetyEventSeverity.medium,
  }) async {
    try {
      final event = SafetyEventModel(
        id: '',
        eventType: SafetyEventType.rideCancellation,
        incidentType: SafetyIncidentType.other,
        reporterId: userId,
        reportedUserId: null,
        rideId: rideId,
        title: 'Safety-Related Ride Cancellation',
        description: 'User cancelled ride for safety reasons: $reason',
        severity: severity,
        status: SafetyEventStatus.pending,
        location: null,
        evidence: [],
        metadata: {
          'cancellationReason': reason,
          'cancellationType': 'safety',
        },
        timestamp: DateTime.now(),
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        tags: ['cancellation', 'safety', severity.name],
        isAnonymous: false,
        systemData: {
          'autoGenerated': true,
          'sourceService': 'ride_cancellation',
        },
      );

      return await createSafetyEvent(event);
    } catch (e) {
      debugPrint('Error logging safety cancellation: $e');
      return null;
    }
  }

  // Get safety events for a user (their own reports)
  Stream<List<SafetyEventModel>> getUserSafetyEvents(String userId) {
    return _firestore
        .collection(_collection)
        .where('reporterId', isEqualTo: userId)
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs
          .map((doc) => SafetyEventModel.fromFirestore(doc))
          .toList();
    });
  }

  // Get all safety events (admin view)
  Stream<List<SafetyEventModel>> getAllSafetyEvents({
    SafetyEventStatus? status,
    SafetyEventSeverity? severity,
    int limit = 100,
  }) {
    Query query = _firestore
        .collection(_collection)
        .orderBy('createdAt', descending: true);

    if (status != null) {
      query = query.where('status', isEqualTo: status.name);
    }

    if (severity != null) {
      query = query.where('severity', isEqualTo: severity.name);
    }

    return query
        .limit(limit)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs
          .map((doc) => SafetyEventModel.fromFirestore(doc))
          .toList();
    });
  }

  // Update safety event status (admin function)
  Future<bool> updateSafetyEventStatus(
    String eventId,
    SafetyEventStatus status, {
    String? reviewedBy,
    String? reviewNotes,
    String? resolution,
  }) async {
    try {
      final updateData = {
        'status': status.name,
        'updatedAt': Timestamp.fromDate(DateTime.now()),
      };

      if (reviewedBy != null) {
        updateData['reviewedBy'] = reviewedBy;
        updateData['reviewedAt'] = Timestamp.fromDate(DateTime.now());
      }

      if (reviewNotes != null) {
        updateData['reviewNotes'] = reviewNotes;
      }

      if (resolution != null) {
        updateData['resolution'] = resolution;
      }

      await _firestore.collection(_collection).doc(eventId).update(updateData);
      return true;
    } catch (e) {
      debugPrint('Error updating safety event status: $e');
      return false;
    }
  }

  // Get safety event summary/statistics
  Future<SafetyEventSummary> getSafetyEventSummary({
    DateTime? startDate,
    DateTime? endDate,
  }) async {
    try {
      Query query = _firestore.collection(_collection);

      if (startDate != null) {
        query = query.where('createdAt', isGreaterThanOrEqualTo: Timestamp.fromDate(startDate));
      }

      if (endDate != null) {
        query = query.where('createdAt', isLessThanOrEqualTo: Timestamp.fromDate(endDate));
      }

      final snapshot = await query.get();
      final events = snapshot.docs
          .map((doc) => SafetyEventModel.fromFirestore(doc))
          .toList();

      final eventsByType = <SafetyIncidentType, int>{};
      final eventsByUser = <String, int>{};
      int pendingEvents = 0;
      int resolvedEvents = 0;
      int criticalEvents = 0;

      for (final event in events) {
        // Count by incident type
        if (event.incidentType != null) {
          eventsByType[event.incidentType!] = (eventsByType[event.incidentType!] ?? 0) + 1;
        }

        // Count by user
        if (event.reportedUserId != null) {
          eventsByUser[event.reportedUserId!] = (eventsByUser[event.reportedUserId!] ?? 0) + 1;
        }

        // Count by status
        if (event.status == SafetyEventStatus.pending) pendingEvents++;
        if (event.status == SafetyEventStatus.resolved) resolvedEvents++;
        if (event.severity == SafetyEventSeverity.critical) criticalEvents++;
      }

      return SafetyEventSummary(
        totalEvents: events.length,
        pendingEvents: pendingEvents,
        resolvedEvents: resolvedEvents,
        criticalEvents: criticalEvents,
        eventsByType: eventsByType,
        eventsByUser: eventsByUser,
        lastUpdated: DateTime.now(),
      );
    } catch (e) {
      debugPrint('Error getting safety event summary: $e');
      return SafetyEventSummary(
        totalEvents: 0,
        pendingEvents: 0,
        resolvedEvents: 0,
        criticalEvents: 0,
        eventsByType: {},
        eventsByUser: {},
        lastUpdated: DateTime.now(),
      );
    }
  }

  // Private helper methods

  Future<SafetyEventLocation?> _getCurrentLocationForEvent() async {
    try {
      final position = await _locationService.getCurrentLocation();
      return SafetyEventLocation(
        coordinates: position != null 
            ? LatLng(position.latitude, position.longitude) 
            : null,
        accuracy: position?.accuracy,
      );
    } catch (e) {
      debugPrint('Error getting location for safety event: $e');
      return null;
    }
  }

  Future<Map<String, dynamic>> _getDeviceInfo() async {
    // Add device information for forensic purposes
    return {
      'platform': defaultTargetPlatform.toString(),
      'timestamp': DateTime.now().toIso8601String(),
    };
  }

  List<String> _generateTags(SafetyIncidentType incidentType, SafetyEventSeverity severity) {
    final tags = <String>[incidentType.name, severity.name];
    
    if (severity == SafetyEventSeverity.critical) {
      tags.add('urgent');
    }
    
    return tags;
  }

  Future<void> _sendReportConfirmation(String userId, String eventId, bool isAnonymous) async {
    try {
      await _notificationService.createNotification(
        AppNotification(
          id: '',
          userId: userId,
          title: 'Safety Report Submitted',
          message: isAnonymous 
              ? 'Your anonymous safety report has been submitted and will be reviewed.'
              : 'Your safety report has been submitted and will be reviewed. Reference ID: $eventId',
          type: NotificationType.safetyReportConfirmation,
          priority: NotificationPriority.normal,
          isRead: false,
          createdAt: DateTime.now(),
          expiresAt: DateTime.now().add(const Duration(days: 30)),
          data: {'eventId': eventId, 'type': 'safety_report_confirmation'},
        ),
      );
    } catch (e) {
      debugPrint('Error sending report confirmation: $e');
    }
  }

  Future<void> _notifyAdminsOfCriticalEvent(SafetyEventModel event) async {
    // In a real implementation, this would notify all administrators
    debugPrint('CRITICAL SAFETY EVENT: ${event.title} - ID: ${event.id}');
    
    try {
      // Get admin users (in a real implementation, you'd query for admin role)
      final adminIds = await _getAdminUserIds();
      
      for (final adminId in adminIds) {
        await _notificationService.createNotification(
          AppNotification(
            id: '',
            userId: adminId,
            title: 'CRITICAL Safety Event',
            message: 'Critical safety event reported: ${event.title}. Immediate attention required.',
            type: NotificationType.emergencyAlert,
            priority: NotificationPriority.urgent,
            isRead: false,
            isActionable: true,
            actionText: 'Review Event',
            actionRoute: '/admin/safety/${event.id}',
            createdAt: DateTime.now(),
            data: {
              'eventId': event.id,
              'severity': event.severity.name,
              'type': 'critical_safety_event',
            },
          ),
        );
      }
    } catch (e) {
      debugPrint('Error notifying admins of critical event: $e');
    }
  }

  Future<void> _handleEmergencyResponse(SafetyEventModel event) async {
    debugPrint('EMERGENCY BUTTON ACTIVATED: ${event.id}');
    
    try {
      // 1. Immediate admin notification
      await _notifyAdminsOfEmergency(event);
      
      // 2. Get user's emergency contacts and notify them
      if (event.reporterId.isNotEmpty) {
        await _notifyEmergencyContacts(event.reporterId, event);
      }
      
      // 3. Start enhanced location tracking if ride is active
      if (event.rideId != null) {
        await _activateEmergencyLocationTracking(event.rideId!, event.reporterId);
      }
      
      // 4. Create emergency timeline entry
      await _logEmergencyTimeline(event.id, 'emergency_activated', {
        'activatedBy': event.reporterId,
        'rideId': event.rideId,
        'location': event.location?.coordinates != null 
            ? '${event.location!.coordinates!.latitude},${event.location!.coordinates!.longitude}'
            : 'LOCATION_UNAVAILABLE',
        'timestamp': DateTime.now().toIso8601String(),
      });
      
      // 5. Send push notification to user confirming activation
      await _sendEmergencyActivationConfirmation(event.reporterId, event.id);
      
      // 6. Log security event for audit trail
      SecurityUtils.logSecurityEvent('emergency_response_initiated', {
        'eventId': event.id,
        'userId': SecurityUtils.hashData(event.reporterId),
        'rideId': event.rideId,
        'hasLocation': event.location?.coordinates != null,
        'responseTimestamp': DateTime.now().toIso8601String(),
      });
      
    } catch (e) {
      debugPrint('Error in emergency response workflow: $e');
      
      // Even if the workflow fails, ensure admins are notified
      try {
        await _sendFailsafeEmergencyNotification(event.id, e.toString());
      } catch (failsafeError) {
        debugPrint('Critical: Failsafe emergency notification failed: $failsafeError');
      }
    }
  }

  Future<void> _checkMultipleReports(String reportedUserId) async {
    try {
      // Get reports against this user in the last 30 days
      final thirtyDaysAgo = DateTime.now().subtract(const Duration(days: 30));
      final recentReports = await _firestore
          .collection(_collection)
          .where('reportedUserId', isEqualTo: reportedUserId)
          .where('createdAt', isGreaterThan: Timestamp.fromDate(thirtyDaysAgo))
          .get();

      if (recentReports.docs.length >= 3) {
        // Multiple reports detected - notify admins
        debugPrint('MULTIPLE REPORTS DETECTED for user: $reportedUserId (${recentReports.docs.length} reports)');
        
        await _notifyAdminsOfMultipleReports(reportedUserId, recentReports.docs.length);
      }
    } catch (e) {
      debugPrint('Error checking multiple reports: $e');
    }
  }

  Future<void> _notifyAdminsOfMultipleReports(String reportedUserId, int reportCount) async {
    try {
      final adminIds = await _getAdminUserIds();
      
      for (final adminId in adminIds) {
        await _notificationService.createNotification(
          AppNotification(
            id: '',
            userId: adminId,
            title: 'Multiple Safety Reports Alert',
            message: 'User $reportedUserId has received $reportCount safety reports in the last 30 days. Review required.',
            type: NotificationType.emergencyAlert,
            priority: NotificationPriority.high,
            isRead: false,
            isActionable: true,
            actionText: 'Review Reports',
            actionRoute: '/admin/safety?user=$reportedUserId',
            createdAt: DateTime.now(),
            data: {
              'reportedUserId': reportedUserId,
              'reportCount': reportCount,
              'type': 'multiple_reports_alert',
            },
          ),
        );
      }
    } catch (e) {
      debugPrint('Error notifying admins of multiple reports: $e');
    }
  }

  // Helper method to get admin user IDs
  // In a real implementation, this would query users with admin role
  Future<List<String>> _getAdminUserIds() async {
    try {
      // For now, return a hardcoded list of admin IDs
      // In production, query users collection for admin role
      final admins = await _firestore
          .collection('users')
          .where('accountType', isEqualTo: 'admin')
          .get();
      
      return admins.docs.map((doc) => doc.id).toList();
    } catch (e) {
      debugPrint('Error getting admin user IDs: $e');
      // Return empty list if query fails
      return [];
    }
  }

  // Emergency Response Workflow Methods

  Future<void> _notifyAdminsOfEmergency(SafetyEventModel event) async {
    try {
      final adminIds = await _getAdminUserIds();
      
      for (final adminId in adminIds) {
        await _notificationService.createNotification(
          AppNotification(
            id: '',
            userId: adminId,
            title: '🚨 EMERGENCY ACTIVATION',
            message: 'Emergency button activated! User needs immediate assistance. Location: ${_getLocationString(event.location)}',
            type: NotificationType.emergencyAlert,
            priority: NotificationPriority.urgent,
            isRead: false,
            isActionable: true,
            actionText: 'Respond Now',
            actionRoute: '/admin/emergency/${event.id}',
            createdAt: DateTime.now(),
            data: {
              'eventId': event.id,
              'userId': event.reporterId,
              'rideId': event.rideId,
              'type': 'emergency_activation',
              'requiresImmediateResponse': true,
            },
          ),
        );
      }
    } catch (e) {
      debugPrint('Error notifying admins of emergency: $e');
    }
  }

  Future<void> _notifyEmergencyContacts(String userId, SafetyEventModel event) async {
    try {
      // Get user's emergency contacts from user document
      final userDoc = await _firestore.collection('users').doc(userId).get();
      
      if (userDoc.exists) {
        final userData = userDoc.data() as Map<String, dynamic>;
        final emergencyContacts = userData['emergencyContacts'] as List<dynamic>? ?? [];
        
        for (final contactData in emergencyContacts) {
          final contact = contactData as Map<String, dynamic>;
          
          // Create emergency contact notification entry for external processing
          await _createEmergencyContactNotification(
            contactData: contact,
            event: event,
            userDisplayName: userData['displayName'] ?? 'CavPool User',
          );
        }
      }
    } catch (e) {
      debugPrint('Error notifying emergency contacts: $e');
    }
  }

  Future<void> _createEmergencyContactNotification({
    required Map<String, dynamic> contactData,
    required SafetyEventModel event,
    required String userDisplayName,
  }) async {
    try {
      final locationString = _getLocationString(event.location);
      final message = '''
🚨 EMERGENCY ALERT 🚨

$userDisplayName has activated their emergency button and may need immediate assistance.

Time: ${DateTime.now().toString().split('.')[0]}
Location: $locationString
${event.rideId != null ? 'During ride: ${event.rideId}' : 'Not during active ride'}

This is an automated emergency notification from CavPool Safety System.

If this is a life-threatening emergency, call 911 immediately.
      '''.trim();

      // Store notification for external SMS/email processing
      await _firestore.collection('emergency_notifications').add({
        'contactName': contactData['name'] ?? 'Emergency Contact',
        'contactPhone': contactData['phoneNumber'] ?? '',
        'contactEmail': contactData['email'] ?? '',
        'message': message,
        'eventId': event.id,
        'userId': event.reporterId,
        'userDisplayName': userDisplayName,
        'location': locationString,
        'rideId': event.rideId,
        'priority': 'emergency',
        'status': 'pending',
        'createdAt': Timestamp.fromDate(DateTime.now()),
        'deliveryMethods': ['sms', 'email'], // Both SMS and email for redundancy
      });

      // Also send immediate notification via delivery service
      final phoneNumber = contactData['phoneNumber'] ?? '';
      final email = contactData['email'] ?? '';
      
      if (phoneNumber.isNotEmpty || email.isNotEmpty) {
        await _deliveryService.sendEmergencyNotification(
          phoneNumber: phoneNumber,
          email: email,
          message: message,
          emergencyType: 'emergency',
        );
      }

      debugPrint('Emergency contact notification sent to: ${contactData['name']}');
    } catch (e) {
      debugPrint('Error creating emergency contact notification: $e');
    }
  }

  Future<void> _activateEmergencyLocationTracking(String rideId, String userId) async {
    try {
      // Create enhanced tracking record for emergency
      await _firestore.collection('emergency_tracking').doc(rideId).set({
        'rideId': rideId,
        'userId': userId,
        'emergencyActivated': true,
        'trackingStarted': Timestamp.fromDate(DateTime.now()),
        'trackingFrequency': 'high', // More frequent location updates
        'status': 'active',
        'lastLocationUpdate': null,
        'metadata': {
          'reason': 'emergency_button_activation',
          'priority': 'critical',
        },
      });

      debugPrint('Emergency location tracking activated for ride: $rideId');
    } catch (e) {
      debugPrint('Error activating emergency location tracking: $e');
    }
  }

  Future<void> _logEmergencyTimeline(String eventId, String action, Map<String, dynamic> data) async {
    try {
      await _firestore.collection('emergency_timeline').add({
        'eventId': eventId,
        'action': action,
        'timestamp': Timestamp.fromDate(DateTime.now()),
        'data': data,
        'sequenceId': DateTime.now().millisecondsSinceEpoch,
      });
    } catch (e) {
      debugPrint('Error logging emergency timeline: $e');
    }
  }

  Future<void> _sendEmergencyActivationConfirmation(String userId, String eventId) async {
    try {
      await _notificationService.createNotification(
        AppNotification(
          id: '',
          userId: userId,
          title: '🚨 Emergency Activated',
          message: 'Emergency mode is now active. Help is on the way. Safety team and your emergency contacts have been notified.',
          type: NotificationType.emergencyAlert,
          priority: NotificationPriority.urgent,
          isRead: false,
          isActionable: true,
          actionText: 'View Status',
          actionRoute: '/emergency/status/$eventId',
          createdAt: DateTime.now(),
          expiresAt: DateTime.now().add(const Duration(hours: 24)),
          data: {
            'eventId': eventId,
            'type': 'emergency_confirmation',
          },
        ),
      );
    } catch (e) {
      debugPrint('Error sending emergency activation confirmation: $e');
    }
  }

  Future<void> _sendFailsafeEmergencyNotification(String eventId, String error) async {
    try {
      // Create a failsafe notification record that can be processed by external monitoring
      await _firestore.collection('emergency_failsafe').add({
        'eventId': eventId,
        'error': error,
        'timestamp': Timestamp.fromDate(DateTime.now()),
        'severity': 'critical',
        'requiresManualIntervention': true,
        'message': 'Emergency response workflow partially failed. Manual intervention required.',
      });

      debugPrint('Failsafe emergency notification created for event: $eventId');
    } catch (e) {
      debugPrint('Critical failsafe notification creation failed: $e');
    }
  }

  String _getLocationString(SafetyEventLocation? location) {
    if (location?.coordinates != null) {
      final lat = location!.coordinates!.latitude.toStringAsFixed(6);
      final lng = location.coordinates!.longitude.toStringAsFixed(6);
      final accuracy = location.accuracy != null ? ' (±${location.accuracy!.toStringAsFixed(0)}m)' : '';
      return 'https://maps.google.com/?q=$lat,$lng$accuracy';
    }
    return 'Location unavailable';
  }
}